--CREATE DATABASE PRUEBAS
--GO

USE PRUEBAS
GO
----CONSULTAR INFORMACION DE LAS TABLAS
---DML -> SELECT
/*
Permite mostrar los datos de una tabla
*/

------------
DROP TABLE EMPLEADO
CREATE TABLE EMPLEADO(
COD_EMPLEADO INT NOT NULL,
NOMBRE_COMPLETO VARCHAR(100),
FECHA_NAC DATE,
FECHA_INGRESO DATETIME,
SUELDO NUMERIC(10,2),
ES_NUEVO BIT
)
--MOSTRAR TODA LA INFORMACION DE UNA TABLA
---EL * REPRESENTA TODAS LAS COLUMNAS
SELECT *
FROM EMPLEADO

---MOSTRAR UNA COLMNA EXISTENTE AL COMIENZO Y LUEGO MOTRAR TODAS LAS DEMAS COLUMNAS
SELECT ES_NUEVO, *
FROM EMPLEADO

--MOSTRAR SOLO INFORMACION DESEADA DE UNA TABLA
---SE COLOCAN LAS COLUMNAS SEPARADAS POR COMA EN EL ORDEN DESEADO
SELECT COD_EMPLEADO, NOMBRE_COMPLETO, SUELDO
FROM EMPLEADO

SELECT *---FUNCIONES--DISTINCT --TOP
---INTO --CREAR NUEVAS TABLAS A PARTIR DE UNA EXISTENTE
FROM EMPLEADO
--JOIN ---SIRVEN PARA UNIR TABLAS
--WHERE ----USADO PARA FILTROS
--GROUP BY --USADO PARA AGRUPAR AL HACER CALCULOS
--HAVING --USADO PARA FILTRAR LOS GRUPOS
--ORDER BY --USADO PARA ORDENAR LOS DATOS
---------------------------------------

--COMANDO AS
----PERMITE CAMBIAR EL NOMBRE DE UNA COLUMNA, SOLO CUANDO SE MUESTRA EL RESULTADO, NO EN LA BASE DE DATOS
SELECT COD_EMPLEADO AS CODIGO, 
NOMBRE_COMPLETO AS NOMBRE_EMPLEADO
FROM EMPLEADO


--COMANDOS QUE SE PUEDEN UTILIZAR DENTRO DE UN SELECT
---TOP
-----PERMITE LIMITAR LOS RESULTADOS OBTENIDOS DE UNA CONSULTA SEGUN EL NUMERO QUE SE COLOQUE DENTRO DE LOS PARENTESIS
SELECT TOP(5) *
FROM EMPLEADO

---DISTINCT
------PERMITE MOSTRAR LOS RESULTADOS UNICOS DE UNA CONSULTA, SI AL MENOS 1 COLUMNA NO ES IGUAL, ESTOS NO SE AGRUPAN
SELECT DISTINCT *
FROM EMPLEADO

/*
NOTA: TANTO PARA TOP COMO PARA DISTINCT SE PUEDEN SELECCIONAR COLUMNAS UNA A UNA SEPARADAS POR COMA
*/