--CREATE DATABASE PRUEBAS
--GO

USE PRUEBAS
GO
--WHERE
-----PERMITE REALIZAR FILTROS A LAS CONSULTAS GENERADAS
-----ESTE COMANDO SE PUEDE UTILIZAR DENTRO DE UN DELETE Y UPDATE
------------
DROP TABLE EMPLEADO
CREATE TABLE EMPLEADO(
COD_EMPLEADO INT NOT NULL,
NOMBRE_COMPLETO VARCHAR(100),
FECHA_NAC DATE,
FECHA_INGRESO DATETIME,
SUELDO NUMERIC(10,2),
ES_NUEVO BIT
)

------MUESTRA SOLO LOS RESULTADOS EN DONDE EL CODIGO EMPLEADO SEA IGUAL A 1
SELECT *
FROM EMPLEADO 
WHERE COD_EMPLEADO = 1

---------------------------------------
/*
SE PUEDEN UTILIZAR LOS SIGUIENTES COMANDOS 
	OPERADORES ARITMETICOS(FUNCIONA CON TODOS LOS TIPOS DE DATOS QUE NO SEAN TEXTO)
		< (MENOR)
		> (MAYOR)
		= (IGUAL)
		<= (MENOS O IGUAL)
		>= (MAYOR O IGUAL)
		<> (DISTINTO O NO IGUAL)
		!= (DISTINTO O NO IGUAL)
	OPERADORES ESPECIALES
		IN
		BETWEEN 
		LIKE 
	OPERADORES LOGICOS
		AND
		OR
		NOT
*/

---ALGUNOS EJEMPLOS CON OPERADORES ARITMETICOS 
SELECT *
FROM EMPLEADO 
WHERE SUELDO > 3500

SELECT *
FROM EMPLEADO 
WHERE SUELDO <= 3500

SELECT *
FROM EMPLEADO 
WHERE COD_EMPLEADO != 1
--------
--COMANDO IN
----PERMITE SELECCIONAR VARIOS VALORES DE UNA COLUNNA AL MISMO TIEMPO
----LA BUSQUEDA ES EXACTA, POR LO QUE SI NO EXISTE EL VALOR QUE SE ESTA BISCANDO ESTA NO MOSTRARA NIGUN RESULTADO
SELECT *
FROM EMPLEADO
WHERE COD_EMPLEADO IN (1,5,10)
-----SI SE DESEAN VER TODOS LOS VALORES EXCEPTO ALGUNOS SE ANTEPONE EL COMANDO NOT
SELECT *
FROM EMPLEADO
WHERE COD_EMPLEADO NOT IN (1,5,10)

-------
--COMANDO BETWEEN
----PERMITE SELCCIONAR UN RANGO DE FECHAS O NUMEROS
------POR EJEMPLO, EMPLEADOS QUE TIENEN UN SUELDO ENTRE 3000 Y 4000
SELECT * 
FROM EMPLEADO
WHERE SUELDO BETWEEN 3000 AND 4000
------EMPLEADOS QUE NACIERON ENTRE 1 DE ENERO DE 1990 Y 31 DE DICIEMBRE DE 2000
SELECT * 
FROM EMPLEADO
WHERE FECHA_NAC BETWEEN '1990-01-01' AND '2000-12-31'

----------SI SE DESEA EXCLUIR DICHO RANGO Y MOSTRAR TODOS LOS DEMAS RESULTADOS SE ANTEPONE EL COMANDO NOT
------POR EJEMPLO, EMPLEADOS QUE NO TIENEN UN SUELDO ENTRE 3000 Y 4000
SELECT * 
FROM EMPLEADO
WHERE SUELDO NOT BETWEEN 3000 AND 4000
------EMPLEADOS QUE NO NACIERON ENTRE 1 DE ENERO DE 1990 Y 31 DE DICIEMBRE DE 2000
SELECT * 
FROM EMPLEADO
WHERE FECHA_NAC NOT BETWEEN '1990-01-01' AND '2000-12-31'

--COMANDO LIKE
----FUNCIONA IGUAL QUE EL SIGNO IGUAL A (=) PERO PARA LAS COLUMNAS TIPO TEXTO, SI SE DESEA EXCLUIR ALGUNOS RESULTADOS SE PUEDE ANTEPONER EL COMANDO NOT
-------BUSQUEDA EXACTA
SELECT *
FROM EMPLEADO
WHERE NOMBRE_COMPLETO LIKE 'ERICK'
-------INICIAN CON E
SELECT *
FROM EMPLEADO
WHERE NOMBRE_COMPLETO LIKE 'E%'
-------TERMINAN CON E
SELECT *
FROM EMPLEADO
WHERE NOMBRE_COMPLETO LIKE '%E'
-------QUE CONTENGAN LA PALABRA ER
SELECT *
FROM EMPLEADO
WHERE NOMBRE_COMPLETO LIKE '%ER%'
/*
NOTA: EL COMANDO LIKE TIENE MAS USOS, PARA PODER VER MAS INFORMACION DE ELLOS PUEDE CONSULTAR EL SIGUIENTE LINK:
https://www.sqlshack.com/es/introduccion-y-resumen-del-operador-logico-sql-like/
*/