IF OBJECT_ID('tempdb..#DATOS') IS NOT NULL
DROP TABLE #DATOS
SELECT
C.COD_CLIENTE, C.NIT, DATEADD(DAY,CONVERT(INT,-DBO.getRandomNumber(1,180)),V.FECHA_SALIDA) FECHA, B.COD_BOLETO
INTO #DATOS
FROM BOLETO B
JOIN VUELO V ON B.COD_VUELO = V.COD_VUELO
JOIN PASAJERO P ON P.COD_PASAJERO = B.COD_PASAJERO
JOIN CLIENTE C ON C.COD_CLIENTE = P.COD_CLIENTE


TRUNCATE TABLE DETALLE_FACTURA
------------
DELETE FROM FACTURA
INSERT INTO FACTURA(COD_CLIENTE, NIT, FECHA_FACTURA)
SELECT COD_CLIENTE, NIT, FECHA 
FROM #DATOS

-----------------------------
INSERT INTO DETALLE_FACTURA(COD_FACTURA, PRECIO, COD_BOLETO)
SELECT COD_FACTURA, DBO.getRandomNumber(3000, 8000) PRECIO, COD_BOLETO
FROM (
SELECT F.*, ROW_NUMBER() OVER(PARTITION BY COD_BOLETO ORDER BY FECHA) RN, D.COD_BOLETO
FROM #DATOS D
JOIN FACTURA F ON D.COD_CLIENTE = F.COD_CLIENTE AND D.FECHA = F.FECHA_FACTURA
--WHERE F.COD_CLIENTE = 11230 AND FECHA = '20230325'
) A
WHERE RN = 1

--
